services:
  web:
    container_name: ocp-api
    build:
      context: OCP.API
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ocp_db;Username=ocp_user;Password=ocp_pass"
    ports:
      - "3000:8080"
    depends_on:
      db:
        condition: service_healthy # waits for Postgres health check
    restart: on-failure
    networks:
      - ocp-net

  db:
    image: postgres:17.6-alpine3.22
    container_name: ocp-postgres
    environment:
      POSTGRES_DB: ocp_db
      POSTGRES_USER: ocp_user
      POSTGRES_PASSWORD: ocp_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ocp_user -d ocp_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ocp-net

volumes:
  pgdata:

networks:
  ocp-net:
    driver: bridge
